config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root
  root to: 'entry#index'

  # entry
  get '/entry/new', to: 'entry#new'
  match '/entry/:id', to: 'entry#view', via: 'get', as: 'entry', constraints: {id: /[0-9]+/}

  # static pages
  match '/about', to: 'about#view', via: 'get'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :spendings
end

app/models/spending.rb
class Spending < ActiveRecord::Base
  belongs_to :entry
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def view
    render 'pages/about'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController

  before_filter :authenticate_user!, :only => [:new]

  def index
  end

  def view
  end

  def new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/views/entry/index.html.slim
h1 Entry#index

app/views/entry/new.html.slim
h1 Entry#new

app/views/entry/view.html.slim
h1 Entry#view
p Find me in app/views/entry/view.html.slim

app/views/layouts/_footer.html.slim
.container
  p.text-center.copyright
    = link_to 'http://www.funnythingz.com', :target => 'blank'
      | &copy; #{Settings.info[:author]}

app/views/layouts/_global_navigation.html.slim
nav.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target="#menu" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, :class => 'navbar-brand'
        | #{Settings.info.app_name}
    #menu.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to about_path
            | About
        - if user_signed_in?
          li
            = link_to entry_new_path
              | New
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to destroy_user_session_path, :method => :delete
              | Sign out
        - else
          li
            = link_to new_user_registration_path
              | Sign up
          li
            = link_to new_user_session_path
              | Sign in

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target="#menu" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  Budgetter
    #menu.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          = link_to entry_new_path
            | New
      ul.nav.navbar-nav.navbar-right
        li
          = link_to about_path
            | About

app/views/layouts/application.html.slim
Doctype html
html
  head
    title
      | Budgetter

    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    = render 'layouts/global_navigation'

    .container
      p.notice
        | #{notice}
      p.alert
        | #{alert}

      = yield
    = render 'layouts/footer'

app/views/pages/about.html.slim
.container
  h1
    | about

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    br